services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"
    command: php -S 0.0.0.0:8000 -t public
networks:
  symfony: